movies/film_info/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.homepage, name='homepage'),
    path(r'register/', views.register, name='register'),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path('reviewpage/<int:review_id>', views.reviewpage, name='reviewpage'),
    path("filmformpage/", views.filmformpage, name="filmformpage"),


]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path (r'', include(('film_info.urls', 'film_info'), namespace='film_info')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/film_info/models.py
from django.db import models
from django.contrib.auth.models import User

from django.conf import settings
from django.urls import reverse

class Film(models.Model):
    film_title=models.CharField(max_length=200)
    year = models.PositiveSmallIntegerField(blank=True, null=True)
    genre=models.CharField(max_length=100)
    image = models.ImageField(upload_to = 'media/', blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.film_title

    class Meta:
        ordering=['film_title']

    def get_queryset(self):
        return Film.objects.all()


class Review(models.Model):
    summary=models.TextField(null=True)
    review=models.TextField()
    review_film=models.ForeignKey(Film, default=1, on_delete = models.SET_DEFAULT)

    def __str__(self):
        return self.summary


    def get_queryset(self):
        return Review.objects.all()


class Comment(models.Model):
    post = models.ForeignKey(Film, default=1, on_delete = models.SET_DEFAULT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete = models.SET_DEFAULT)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.post

    def __str__(self):
        return self.content

    def get_queryset(self):
        return Comment.objects.all()

    # def __str__(self):
    #     return 'Comment by {} on {}'.format(self.user, self.post)

    class Meta:
        ordering = ('timestamp',)

movies/film_info/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Film, Review, Comment
from django.forms import modelformset_factory



class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ('film_title', 'year', 'genre', 'image', )

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('summary', 'review')

movies/film_info/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect

from .models import Film, Review, Comment

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout, authenticate

from django.contrib import messages

from .forms import NewUserForm, CommentForm, FilmForm, ReviewForm

from django.template import loader

from django.core.exceptions import ObjectDoesNotExist

from django.forms import modelformset_factory

from django.views.decorators.http import require_POST



def homepage(request):
    return render(request=request, template_name="film_info/home.html", context={"all_movies": Film.objects.all()})




def reviewpage(request, review_id):

    rpage = Review.objects.get(id=review_id)
    film_id = rpage.review_film.id
    cpage = Comment.objects.filter(post=film_id)

    if request.method == "POST":
        form = CommentForm(request.POST or None)

        if form.is_valid():
            cpage = Comment.objects.filter(post=film_id)
            content=request.POST.get('content')
            cc=Comment.objects.create( post_id=film_id, user=request.user, content=content)

            cc.save()

            form=CommentForm()
    else:
        form=CommentForm()

    context={'rpage':rpage, 'cpage':cpage, 'form':form}
    return render(request=request, template_name="film_info/reviewpage.html", context=context)



def filmformpage(request):

    if request.method == "POST":
        fform = FilmForm(request.POST, request.FILES)

        if fform.is_valid():
            film_title=request.POST.get('film_title')
            year=request.POST.get('year')
            genre=request.POST.get('genre')
            image = fform.cleaned_data['image']


            ff=Film.objects.create(film_title=film_title, year=year, genre=genre, image=image)
            ff.save()
            fform = FilmForm()
    else:
        fform=FilmForm()

    if request.method == "POST":
        rform = ReviewForm(request.POST, request.FILES)

        if rform.is_valid():
            summary=request.POST.get('summary')
            review=request.POST.get('review')

            rf=Review.objects.create( summary=summary)
            rf.review=review
            rf.review_film_id=ff.id
            rf.save()
            rform = ReviewForm()
    else:
        rform=ReviewForm()

    context={'fform':fform, 'rform':rform}
    return render(request=request, template_name="film_info/filmformpage.html", context=context)




def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username= form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            return redirect("film_info:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = NewUserForm
    return render(request=request, template_name="film_info/register.html", context={"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out")
    return redirect("film_info:homepage")


def login_request(request):
    if request.method == "POST":
        form= AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("film_info:homepage")
            else:
                messages.error(request, "Invalid Username or Password")
        else:
            messages.error(request, "Invalid Username or Password")
    form = AuthenticationForm()
    return render(request, "film_info/login.html", {"form":form})

movies/film_info/templates/film_info/filmformpage.html
{%extends "film_info/header.html" %}

{%block content%}

<a href="{% url 'film_info:homepage' %}" style="color:teal">&lt; Back</a>
<br></br>

<div class="row">
  <form method="POST" class="col s12" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ fform.as_p }}
    <br></br>
    {{ rform.as_p }}

    <!-- <div class="row">
    <div class="col-25"> -->
      <!-- <label for="ft">Film Title</label> -->
    <!-- </div>
    <div class="col-75">
      <input type="text" id="ft" name="film title" placeholder="Film Title">
    </div>
  </div>

    <div class="row">
    <div class="col-25"> -->
      <!-- <label for="year">Year</label> -->
    <!-- </div>
    <div class="col-75">
      <input type="number" id="year" name="year" placeholder="Year">
    </div>
  </div>

  <div class="row">
  <div class="col-25"> -->
    <!-- <label for="genre">Genre</label> -->
  <!-- </div>
  <div class="col-75">
    <input type="text" id="genre" name="genre" placeholder="Genre">
  </div>
  </div>
<br></br>
  <div class="row">
  <div class="col-25">
    <label for="image">Upload film image</label>
    <br></br>
  </div>
  <div class="col-75">
    <input type="file"
       id="image" name="image"
       accept="image/png, image/jpeg, image.jpg">
  </div>
  </div> -->


<!--
  <div class="row">
    <div class="input-field col s12">
      <button class="btn " type="submit" background-color= "yellow">Submit</button>
    </div>
  </div>
</form>
</div> -->


<!--
<div class="row">
  <form method="POST" class="col s12">{% csrf_token %} -->
    <!-- {{ rform.as_p }} -->
    <!-- <div class="row">
    <div class="col-25"> -->
      <!-- <label for="summary">Summary</label> -->
    <!-- </div>
    <div class="col-75">
      <textarea id="subject" name="subject" placeholder="Write a film summary" style="height:200px"></textarea>
    </div>
  </div>

    <div class="row">
    <div class="col-25"> -->
      <!-- <label for="rev">Review</label> -->
    <!-- </div>
    <div class="col-75">
      <textarea id="rev" name="rev" placeholder="Write a film review" style="height:200px"></textarea>
    </div>
  </div> -->



    <div class="row">
      <div class="input-field col s12">
        <button class="btn " type="submit" background-color= "yellow">Submit</button>
      </div>
    </div>
  </form>
</div>


{%endblock%}

movies/film_info/templates/film_info/header.html
<head>
  <!-- Compiled and minified CSS -->
   {% load static %}
   <link href=“{% static 'film_info/css/materialize.css' %} rel=“stylesheet”>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

   <!-- Compiled and minified JavaScript -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>
  <h1 class="center-align">MOVIES</h1>
  <br></br>

  <nav>
  <div class="nav-wrapper blue-grey  ">
    <a href="/" class="brand-logo">Films</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="/">Home</a></li>
      {% if user.is_authenticated %}
        <!-- <li><a href="/account">{{user.username}}</a></li> -->
        <li><a href="/logout">Logout</a></li>
        <li><a href="/filmformpage">Add Film</a></li>
      {% else %}
        <li><a href="/register">Register</a></li>
        <li><a href="/login">Login</a></li>
      {% endif %}
    </ul>
  </div>
  </nav>
  {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
  <br></br>
  <div class ="container">
    {%block content%}
    {%endblock%}
  </div>
</body>

movies/film_info/templates/film_info/home.html
{%extends "film_info/header.html" %}

{%block content%}

  <!-- <div class="row">
    {%for am in all_movies%}
      <div class="col s12 m6">
        <div class="card purple lighten-4">
          <div class="card-content black-text">
            <span class="card-title"><b>{{am.film_title}}</b>  {% if am.image != None %}
                <img src="{{ am.image.url }}" width="150" height="150" ALIGN=right>
              {% endif %}</span>
            <p>Year Released: {{am.year}}</p>

            <p>Genre: {{am.genre}}</p>
            <br></br>


          </div>
          {% for review in am.review_set.all %}
          <a href=" {% url 'film_info:reviewpage' review_id=review.id %} ">More</a>
          {% endfor %}
        </div>
      </div>
      {%endfor%}
    </div> -->

    <div class="row">
      {%for am in all_movies%}
       <div class="col s6 m5">
         <div class="card">
           <div class="card-image">
             {% if am.image != None %}
              <img src="{{ am.image.url }}" width="150" height="200">
             {% endif %}

           </div>
           <div class="card-content">
             <span class="card-title"><b>{{am.film_title}}</b></span>
             <p>Year Released: {{am.year}}</p>
             <p>Genre: {{am.genre}}</p>
           </div>
           {% for review in am.review_set.all %}
           <div class="card-action">
             <a href=" {% url 'film_info:reviewpage' review_id=review.id %} " style="color:teal">More</a>
          {% endfor %}
           </div>
         </div>
       </div>
       {%endfor%}
     </div>








{%endblock%}

movies/film_info/templates/film_info/login.html
{% extends "film_info/header.html" %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn" type="submit">Login</button>
  </form>

  If you don't already have an account, <a href="/register"><strong>register</strong></a> instead

{% endblock %}

movies/film_info/templates/film_info/register.html
{% extends "film_info/header.html" %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn" type="submit">Register</button>
  </form>

  If you already have an account, <a href="/login"><strong>login</strong></a> instead

{% endblock %}

movies/film_info/templates/film_info/reviewpage.html
{%extends "film_info/header.html" %}

{%block content%}

      <a href="{% url 'film_info:homepage' %}" style="color:teal">&lt; Back</a>
      <h1>{{rpage.review_film}}</h1>
      <p><b>Summary:</b> {{rpage.summary}}</p>
      
      <p><b>Review:</b> {{rpage.review}}</p>


      <br></br>

      <h3>Comments</h3>
      <br></br>
      <div class="row">
        <form method="POST" class="col s12">{% csrf_token %}
          <!-- {{ form.as_p }} -->
          <p><label style="font-size:17px" for="id_content">Leave a comment</label>
            <input id="id_content" type="text" name="content" maxlength="500" required /></p>

          <div class="row">
            <div class="input-field col s12">
              <!-- <input id="content" type="text" class="validate">
              <label for="content">Leave a comment</label> -->
              <!-- <textarea id="textarea1" class="materialize-textarea"></textarea>
              <label for="textarea1">Write a comment</label> -->
            {% if request.user.is_authenticated %}
              <button class="btn " type="submit" background-color= "yellow">Submit</button>
            {% else %}
              <button class="btn" type="submit" disabled>Login to comment</button>

            {% endif %}
            </div>
          </div>
        </form>
      </div>




<!-- {% with comments.count as total_comments %}
  <b> {{ total_comments }} comment{{ total_comments|pluralize }} </b>
{% endwith %} -->

<!--
{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.user }}
      {{ comment.timestamp }}
    </p>
        {{ comment.content|linebreaks }}
  </div>
  {% empty %}
  <p>There are no comments yet.</p>
  {% endfor %} -->

      <b>{{ cpage.count }} Comment{{ cpage|pluralize }}</b>
      <br></br>
      <br></br>
      {% for c in cpage %}
        {{ c.content }}
        <br></br>
        {{ c.user|capfirst }}, {{ c.timestamp }}
        <br></br>
        <br></br>
      {% endfor %}

      {%endblock%}